### ISSUE TITLE
BACK - Gerenciar variáveis de ambiente em banco de dados

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#142]
## Tarefas
- [x] Usar variáveis do banco
  - #143 
- [x] Correção: impedir seed de crashar e ignorar tabelas
  - #144
- [x] Correção: flag para desativar envio de email do relatório
  - #147
- [ ] Merge em prod
  - [x] [feature/#142-env-db](https://github.com/RJ-SMTR/api-cct/tree/feature/%23142-env-db)
    - #146
  - [x] [hotfix/#142-env-db-crash](https://github.com/RJ-SMTR/api-cct/tree/hotfix/%23142-env-db-crash)
    - #146
  - [ ] [hotfix/#142-flag-mail-report](https://github.com/RJ-SMTR/api-cct/tree/hotfix/%23142-flag-mail-report)
    - #148 
- [ ] Deletar branches em prod
  - [ ] [feature/#142-env-db](https://github.com/RJ-SMTR/api-cct/tree/feature/%23142-env-db)
  - [ ] [hotfix/#142-env-db-crash](https://github.com/RJ-SMTR/api-cct/tree/hotfix/%23142-env-db-crash)

## Contexto

Para evitar redeploy de servidor a cada alteração, variáveis mais recorrentes serão armazenadas em banco de dados na tabela **setting**.

## Estrutura

id | name | value | version | editable | settingTypeId
-- | -- | -- | -- | -- | --
5 | poll_db_enabled | `false` | _null_  | false | `1` (boolean)
6 | poll_db_cronjob | `30 * * *` | _null_ | false | `2` (string)
7 | mail_invite_cronjob | `* * * *` | _null_ | false | `2` (string)
8 | mail_report_cronjob | `* * * *` | _null_ | false | `2` (string)
9 | mail_report_enabled | `false` | _null_ | false | `1` (boolean)
