### ISSUE TITLE
Criar rota de cadastro

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#16]
# TODO

Planejamento inicial
- [x] Alinhar o que e onde o permissionário será cadastrado no banco
- [x] Adicionar campos para cadastro, caso precise
- [x] Criar arquivos e configs necessários  (banco, service, validation etc)
- [x] Implementar rota

Após revisão dos requisitos ([comentário abaixo](https://github.com/RJ-SMTR/api-cct/issues/16#issuecomment-1614647752))
- [x] Criar mock do Core bancário
- [x] Criar situação Ativo/Inativo para o usuário
- [x] Implementar dados requisitados
- [x] Alinhar o que será implementado ou alterado
- [x] Testar no docker, conflitos de merge e publicar branch
