### ISSUE TITLE
BACK - Remover dados simulados do financeiro

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#168]
## Situação

**25/01/2024**
Para garantir que os testes de integração do financeiro batem eles estão sendo ajustados para usar dados reais de algum usuário, simulando uma situação real.

**24/01/2023**
O impedimento das colunas alteradas no BigQuery foi resolvido.
É importante lembrar, contudo, que é preciso criar uma conta de API exclusiva para homologação e produção. Além de mantermos uma conta de API para desenvolvimento local.

**18/01/2024**
Os dados simulados do CoreBank (CNAB) foram removidos, porém ainda não temos o sistema de CNAB para obter o status do pagamento, estamos usando `status = nulo` por enquanto.
Descobriu-se que ainda é preciso remover os dados simulados da Jaé. Ele não é mais útil e será removido pois já obtemos as receitas de ticket do bigquery.

**17/01/2024**
Nos endpoints responsáveis pela tela de resumo financeiro iremos usar os dados do bigquery ao invés de dados simulados, se ainda houver.

## Tarefas

- [x] Remover dados simulados e usar dados vazios se necessário
- [x] Atualizar testes após a remoção ([detalhes neste comentário](https://github.com/RJ-SMTR/api-cct/issues/168#issuecomment-1898779716))
- [x] Resolver impedimentos do bigquery ([detalhes neste comentáiro](https://github.com/RJ-SMTR/api-cct/issues/168#issuecomment-1900546567))
- [x] Atualizar testes após resolução do impedimento
- [x] Merge para dev
  - #171
- [ ] Merge para prod (de dev)
- [ ] Remover branch

## Impedimentos

- [x] 18/02/2024: O campo `permissao` (código de permissionário) foi removido do bigquery, equipe de dados. Não é possível obter dados financeiros sem este campo ([detalhes neste comentário](https://github.com/RJ-SMTR/api-cct/issues/168#issuecomment-1900546567))
  - 22/01/2024: Aguardando liberarem o acesso à coluna `operadoras.documento`.
    > Enquanto não liberam o acesso ao banco, nosso código já pode se preparar para a leitura da tabela.
  - 24/01/2024: Foi liberado acesso para o email interno da API apenas, permitindo que a API visualize os CPFs. O impedimento foi resolvido.

**Comment by yxuo** [comment]
## Como será feito

Os dados simulados atualmente são usados da seguinte forma:

![Image](https://github.com/RJ-SMTR/api-cct/assets/54970870/61bdc00c-7e2e-483e-81d4-0c8ce24a52bc)

Remover os dados simulados no Cronjob e AuthService é simples, o desafio será entender e alinhar se é possível usar os dados financeiros do bigquery para obter o resumo semanal neste momento.

**Comment by yxuo** [comment]
## Reafirmando os requisitos dos dados financeiros do api-cct

BankStatements (extrato semanal)
- 1: Ao filtrar as últimas 2 semanas deve retornar os dias da semana atual + os da semana anterior
  > Exemplo: Se hoje é 22/01/2023 deve retornar as semanas 27/01 (semana atual) e 20/01.
  > Cada semana vai somar os dias de sua semana (via TicketRevenues). Os dias vão de 12/01 até 25/01/2023 (mas só terá dados até o dia 22, o dia atual)

- 2: Ao filtrar a última semana deve retornar os dias da semana atual + os da semana anterior
  > Exemplo: Se hoje é 25/01/2023 deve retornar a semana 27/01 (semana atual).
  > Esta semana vai somar os dias dessa semana (via TicketRevenues). Os dias vão de 19/01 até 25/01/2023 (coincidentemente é o dia atual).

- 3: Ao filtrar o mês todo deve retornar desde a 1a semana do mês até a semana atual do mês.
  > Exemplo: Se hoje é 17/01/2023 deve retornar as semanas 06/01 até 20/01 (semana atual).
  > As semanas somam os dias de sua semana (via TicketRevenues). Os dias vão de 29/12/2022 (semana 06/01) até 18/01/2023 (semana atual, porém só terá dados até o dia 17).

- 4: Ao filtrar intervalo de tempo em BankStatements retornará erro, pois não será usado no momento.

- 5: Se usuário não existe, retorna erro.

**Comment by yxuo** [comment]
## Ajustar testes após a remoção

Foram atualizados os testes do módulo BankStatements pois era necessário para garantir que o sistema funcionaria.
Os demais testes serão atualizados após a remoção dos dados simulados, para fins de organização.

### Receita de passagens

**ticket-revenues.service.spec.ts:**

Havia testes para dados simulados ([descritos na issue #80](https://github.com/RJ-SMTR/api-cct/issues/80#issuecomment-1806153475)). Uma vez que tais dados serão removidos, esses testes também seriam removidos.

**ticket-revenues.controler.spec.ts:**

Após alterações no módulo o teste não foi atualizado. Como estamos removendo dados simulados usados por este módulo, é interessante atualizar esse teste também. Contém apenas um teste simples.

**Comment by yxuo** [comment]
## Mudanças no bigquery

- A coluna **id_tipo_pagamento** (int) exigia que nossa API tinha que converter o id em valor (e.g. 21 = "Gratuidade"). Esta coluna foi substituída por **tipo_pagamento**, que já nos envia o valor em string (e.g. "Gratuidade" ao invés de 21).
- A coluna **permissao** foi removida, isto quebra nossa API. É preciso pedir para incluírem novamente esta coluna ou buscar outra maneira de identificar o vanzeiro.

### Query de exemplo

**Query original (não funciona mais):**
```sql
      SELECT
        CAST(data AS STRING) AS partitionDate,
        hora AS processingHour,
        CAST(datetime_transacao AS STRING) AS transactionDateTime,
        CAST(datetime_processamento AS STRING) AS processingDateTime,
        datetime_captura AS captureDateTime,
        modo AS transportType,
        permissao AS permitCode,
        servico AS vehicleService,
        sentido AS directionId,
        id_veiculo AS vehicleId,
        id_cliente AS clientId,
        id_transacao AS transactionId,
        id_tipo_pagamento AS paymentMediaType,
        id_tipo_transacao AS transactionType,
        id_tipo_integracao AS transportIntegrationType,
        id_integracao AS integrationId,
        latitude AS transactionLat,
        longitude AS transactionLon,
        stop_id AS stopId,
        stop_lat AS stopLat,
        stop_lon AS stopLon,
        valor_transacao AS transactionValue,
        versao AS bqDataVersion
      FROM `rj-smtr.br_rj_riodejaneiro_bilhetagem.transacao`
WHERE
  permissao = '213890329890312' AND 
  ((DATE(data) >= DATE('2023-12-07') AND DATE(data) <= DATE('2023-12-13')) OR (DATE(data) = DATE('2024-01-19')))
ORDER BY data DESC, hora DESC
LIMIT 2
```

**Query que não retornaria erro:**
```sql
      SELECT
        CAST(data AS STRING) AS partitionDate,
        hora AS processingHour,
        CAST(datetime_transacao AS STRING) AS transactionDateTime,
        CAST(datetime_processamento AS STRING) AS processingDateTime,
        datetime_captura AS captureDateTime,
        modo AS transportType,
        -- permissao AS permitCode,        -- ❌ removido
        servico AS vehicleService,
        sentido AS directionId,
        id_veiculo AS vehicleId,
        id_cliente AS clientId,
        id_transacao AS transactionId,
        id_tipo_pagamento AS paymentMediaType,
        tipo_transacao AS transactionType,  -- ⚠️ antes era id_tipo_transacao
        id_tipo_integracao AS transportIntegrationType,
        id_integracao AS integrationId,
        latitude AS transactionLat,
        longitude AS transactionLon,
        stop_id AS stopId,
        stop_lat AS stopLat,
        stop_lon AS stopLon,
        valor_transacao AS transactionValue,
        versao AS bqDataVersion
      FROM `rj-smtr.br_rj_riodejaneiro_bilhetagem.transacao`
WHERE
  -- permissao = '213890329890312' AND -- ❌ removido
  ((DATE(data) >= DATE('2023-12-07') AND DATE(data) <= DATE('2023-12-13')) OR (DATE(data) = DATE('2024-01-19')))
ORDER BY data DESC, hora DESC
LIMIT 2
```
