### ISSUE TITLE
Criar rota de pré cadastro - usando mockup para consulta ao SGTU

### ISSUE THREAD

**Issue by gsperim** [RJ-SMTR/api-cct#2]
Relacionado: #8
---

# TODO

Planejamento
- [x] Definir campos necessários do banco
- [x] Definir tipo do banco (MS SQL?)
- [x] Definir se o mockup será um servidor separado.

Execução
- [x] Criar mockup do SGTU
- [x] Criar rota para validar CPF com os dados do SGTU (endpoint de validação)
- [x] Criar rota para retornar dados do SGTU
- [x] Testar no Docker e subir Feature no Github

# Descrição

## Objetivo

O objetivo é a API acessar dados de um banco mockado do SGTU e retornar numa rota.

O front entra na rota autenticado e a API tenta retornar as informações do SGTU relacionadas ao usuário.

## Mockup do SGTU

* Validar CPF com os dados do SGTU
* Retornar dados do SGTU.
* O mockup do SGTU será um servidor mínimo com um database isolados no Docker.

Por hora os dados devem ser assim:
```js
type sgtuDto = {
    cpf: string,
    rg: string,
    autorizacao: string,
    nome: string,
    placa: string,
    telefone: string
}

```

## Funcionamento

SGTU seria a ferramenta de cadastro dos _vanzeiros_.

Nossa API deve acessar 2 bancos de dados: CCT e SGTU.

Mas nessa tarefa vamos focar no SGTU:
```mermaid
graph LR;

  Front["Permissionário \n autenticado \n (Front)"];

  API[API];

  SGTU[("SGTU \n (MS SQL)")];

  CCT[("CCT \n (Postgres)")];

API -- "❇️ Busca permissionário" --> SGTU;
API -- Grava permissionário --> CCT;
Front --> API;
```
