### ISSUE TITLE
rota de extrato

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#31]
## Objetivo

Enquanto não temos a API oficial, será usado um mock desses dados.

Segundo a issue [app-cct #30](https://github.com/RJ-SMTR/app-cct/issues/30), o extrato virá do BI.

## TODO

- [x]  Criar um mock do extrato financeiro para 1 mês.
- [x]  Criar rota que exibe extrato entre a 6ª atual até a próxima 5ª.
- [x]  Criar rota para o histórico de extrato, que seleciona o intervalo no calendário
- [x]  Testar no Docker e subir PR

## Relacionado

- [Extrato Financeiro - app-cct #30](https://github.com/RJ-SMTR/app-cct/issues/30)
- [Histórico do Extrato Financeiro (draft)](https://github.com/orgs/RJ-SMTR/projects/5/views/1?filterQuery=extra&pane=issue&itemId=33681406)
- [❓ tela de extrato (draft, vazio)](https://github.com/orgs/RJ-SMTR/projects/5/views/1?filterQuery=extra&pane=issue&itemId=31754360)
- [❓ integração com o core bancário para receber dados de extratos (draft, vazio)](https://github.com/orgs/RJ-SMTR/projects/5/views/1?filterQuery=extra&pane=issue&itemId=31754497)
