### ISSUE TITLE
Rota de resumo das viagens

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#33]
## Objetivo

Entregar uma rota com dados mockados com o dinheiro arrecadado em viagens por dia.

## TODO

- [x]  Estudar e revisar o contexto que resulta na entrega de resumo das viagens
- [x]  Criar módulo `trips-income`
- [x]  Criar mock dos dados
- [x]  Criar rota `trips-income`
- [x]  Testar no Docker e subir PR

## Requisitos

- O valor arrecadado das viagens para o dia atual é sempre R$ 0, pois considera-se que o *vanzeiro* ainda está em atividade.
    
    > Requisito de @nairacarrilho numa Sprint Review em 19/07/2023
    > 

## Detalhes

O @Gabriel0109 deu uma amostra de como o valor da viagem arrecadada seria exibido, que é o dia da viagem e o valor arrecadado (já citado em [comentário em #31](https://github.com/RJ-SMTR/api-cct/issues/31#issuecomment-1649785449)):

![Image](https://github.com/RJ-SMTR/api-cct/assets/54970870/de74bff6-3217-4e27-a9ff-6bc3f4075e09)

O formato dos dados será similar aos usados em [#31](https://github.com/RJ-SMTR/api-cct/issues/31#issuecomment-1649785449):

```json
{
  "permissionario": {
    "123": [
      {
        "data": "2023-06-01",
        "valorLiquido": 250.00
      },
    ]
  }
}
```

O documento de repasse da Jaé para a CCT não associa veículos, apenas o número de passagens, o lucro bruto e líquido (após abatimento de imposto).

Para esse mock será usado apenas o essencial: data e valor líquido total, pois não sabemos quais dados a mais serão fornecidos para o front exibir.

## Relacionado

- [Resumo das Viagens (draft)](https://github.com/orgs/RJ-SMTR/projects/5/views/1?filterQuery=viage+&pane=issue&itemId=33678234)
