### ISSUE TITLE
Backend - Implementar testes unitários

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#35]
## Objetivo

- Validar os requisitos da API em diferentes cenários
- Ajudar a diminuir erros e comportamentos inesperados
- Permitir automatizar a validações desejáveis no código (CI/CD)
- Melhorar a qualidade do código

## TODO

- [x] Montar testes unitários para um módulo simples, servindo como exemplo a ser usado
- [ ] Gerar testes unitários para os demais módulos
- [ ] Gerar testes para filters, pipes e validators
- [ ] Ocultar arquivos desnecessários em `jest coverage` (opcional, não urgente)
- [ ] Verificar se é interessante forçar o usuário a sempre criar testes para dar commit.
- [ ] Validar testes e subir PR

### O uso de testes em um projeto

O uso de testes como boa prática de desenvolvimento (TDD) cria um bom hábito de criar testes,  que por si só documentam se o código funciona e quais requisitos, funcionais ou não, devem ser validados.

Isso diminui muito a change de bugs, código legado ou focar no lugar errado, já que induz a equipe (TestDevOps) a sempre focar em quais pontos importantes precisam ser validados antes de fazer o código.

### Por que testes unitários?

Como o projeto não possui nenhum teste, um primeiro passo seria implementar testes unitários, pois focam em um pequeno pedaço do código.

É uma solução rápida e simples, permitindo implementar aos poucos.

E é recomendado fazer primeiro testes unitários ([**Uncle Bob** - StackOverflow](https://stackoverflow.com/questions/601438/when-to-unit-test-vs-manual-test#:~:text=you%20should%20write%20automated%20unit%20tests%20first%20for%20the%20vast%20majority%20of%20the%20code%20you%20write.))

### Próximos passos

Após essa issue, conforme cada submódulo é testado, será possível fazer:

- Teste de Integração
- Teste E2E

Pois é sempre recomendável utilizar mais de um tipo de teste para validar.
